---
- name: Check if pip is installed
  stat:
    path: /bin/pip
  register: pip

- name: Install os packages
  yum: name={{item}} state=present
  with_items:
  - zlib-devel
  - gcc
  - make
  - git
  - autoconf
  - autogen
  - automake
  - pkgconfig
  - unzip
  - bc
  - net-tools
  - nmap-ncat
  - vim
  - python-devel
  - python-setuptools
  ignore_errors: true


- name: Download pip.
  get_url: url=https://bootstrap.pypa.io/get-pip.py dest=/tmp
  when: pip.stat.exists == False

- name: Install pip.
  command: "python /tmp/get-pip.py"
  when: pip.stat.exists == False

- name: install httplib2
  pip:
    name: httplib2
