- name: Check if docker is installed
  stat:
    path: /bin/docker
  register: docker

- name: Check if pip six is installed
  stat:
    path: /usr/lib/python2.7/site-packages/six*
  register: six

- name: Check if pip docker-py is installed
  stat:
    path: /usr/lib/python2.7/site-packages/docker_py*
  register: dockerpy

- name: Install six
  pip: name=six
  when: six.stat.exists == False

- name: Install Docker-Py
  pip: name=docker-py
  when: dockerpy.stat.exists == False

- name: install updates
  yum: update_cache=yes name=docker-engine state=latest disablerepo=extras,extras-source
  when: docker.stat.exists == False
  ignore_errors: yes

- name: Add docker.service
  template:
    src: docker.service.j2
    dest: /usr/lib/systemd/system/docker.service
    mode: 0644
    owner: root
  notify:
    - reload systemd
    - start docker
  ignore_errors: yes
