- name: Check if directories are present
  stat:
    path: /data/jenkins/
  register: directories

- name: Check if config.xml is present
  stat:
    path: /data/jenkins/config.xml
  register: configxml

- name: Directories are present
  file:
    path='{{ item }}'
    state=directory
    mode=0777
  with_items:
    - /data
    - '{{ jenkins_directory }}'
    - '{{ jenkins_directory }}/plugins'
    - '{{ jenkins_directory }}/slaves/{{ groups.jenkinsslave | join(" ") }}'
    - '{{ jenkins_directory }}/nodes/{{ groups.jenkinsslave | join(" ") }}'

- name: slave node config is present
  template:
    src='slaveconfig.xml.j2'
    dest='{{ jenkins_directory }}/nodes/{{ groups.jenkinsslave | join(" ") }}/config.xml'
  when: directories.stat.exists == True

- name: Config files are present
  copy:
    src='{{ item }}'
    dest='{{ jenkins_directory }}/{{ item }}'
    mode=0777
  with_items: configs
  when: configxml.stat.exists == False

- name: Plugins are present
  copy:
    src='plugins/{{ item }}'
    dest='{{ jenkins_directory }}/plugins/{{ item }}'
    mode=0777
  with_items: plugins

- name: Container is running
  docker:
    image: jenkins
    ports: ['8080:8080','50000:50000']
    volumes: /data/jenkins:/var/jenkins_home
    state: started
  register: running_container

- name: Reload
  uri:
    url='http://{{ groups.jenkinsmaster | join(" ") }}:8080/reload'
    method=POST
    status_code=302
  ignore_errors: yes
  when: "'started 1 container' in running_container.msg"
