---
- name: Check if netdata dir exists
  stat:
    path: /var/tmp/netdata
  register: netdata_dir

- name: Check if netdata is cloned from Git
  stat:
    path: /var/tmp/netdata/netdata-installer.sh
  register: netdata_git

- name: Create netdata dir
  file:
    path=/var/tmp/netdata
    state=directory
  when: netdata_dir.stat.exists == False
  
- name: Clone netdata
  git: repo=https://github.com/firehol/{{ item.repo }}.git
       dest={{ item.dest }}
       force=yes
       recursive=no
  with_items:
    -
      dest: "/var/tmp/netdata"
      repo: netdata
  when: netdata_git.stat.exists == False
 
- name: Run Netdata
  command: "cd /var/tmp/netdata && ./netdata-installer.sh --install /data/ --dont-wait"
  when: netdata_git.stat.exists == False
