# Start multiple ec2 instances with instance-specific tags assigned to each
#
- hosts: localhost
  connection: local
  vars:
    ansible_python_interpreter: '/usr/bin/env python'
    ssh_user: 'ec2-user'
    pem_path: "{{ ansible_env.HOME}}/.ssh/myaws.pem"
    group_id: 'sg-7e7a8f16' # jenkins security group - allows 80, 8080, 22, 443
    image: 'ami-875042eb' # RHEL 7.2
    ec2_instances:
      - name: 'jenkinsmaster'
        tags: 
          jenkins: 'master'
        volume_size: 10
      - name: 'jenkinsslave'
        tags: 
          jenkins: 'slave'
        volume_size: 15
  tasks:
    - name: Launch each ec2 Instance
      ec2: 
        keypair: 'myaws'
        group_id: "{{ group_id }}"
        count: 1
        instance_type: 't2.micro'
        volumes:
          - device_name: '/dev/sda1'
            volume_size: "{{ item.volume_size }}"
            delete_on_termination: true
        image: '{{ image }}'
        wait: true
        region: 'eu-central-1'
        aws_access_key: "{{ aws_access_key|default(lookup('env', 'AWS_ACCESS_KEY')) }}"
        aws_secret_key: "{{ aws_secret_key|default(lookup('env', 'AWS_SECRET_KEY')) }}"
        instance_tags: "{{ item.tags }}"
      register: ec2
      with_items: ec2_instances

    - name: 'Wait for SSH'
      wait_for:
        host: "{{ item['instances'][0]['public_ip'] }}"
        port: 22
        delay: 10
        timeout: 320
        state: started
      with_items: ec2.results

    - name: Wait a little longer for centos
      pause: seconds=20

