---
- hosts: all
  connection: local
  remote_user: ec2-user
  vars:
    ansible_python_interpreter: "/usr/bin/env python"
  gather_facts: True
  roles:
    - { role: common, become_method: sudo }
    - { role: docker, become_method: sudo }

- hosts: tag_jenkins_master
  remote_user: ec2-user
  roles:
    - { role: jenkins_master, become_method: sudo, tags: ['jenkinsmaster'] }
    - { role: netdata, become_method: sudo }

- hosts: tag_jenkins_slave
  remote_user: ec2-user
  roles:
    - { role: jenkins_slave, become_method: sudo, tags: [ 'jenkinsslave' ]}
    - { role: netdata, become_method: sudo }

- hosts: registry
  remote_user: ec2-user
  roles:
    - { role: registry, become: yes, become_method: sudo }
