---
- hosts: all
  remote_user: ec2-user
  roles:
    - { role: common, become: yes, become_method: sudo }
    - { role: docker, become: yes, become_method: sudo }

- hosts: jenkinsmaster
  remote_user: ec2-user
  roles:
    - { role: jenkins_master, become: yes, become_method: sudo }
    - { role: netdata, become: yes, become_method: sudo }

- hosts: jenkinsslave
  remote_user: ec2-user
  roles:
    - { role: jenkins_slave, become: yes, become_method: sudo, tags: [ 'jenkinsslave' ]}
    - { role: netdata, become: yes, become_method: sudo }

- hosts: registry
  remote_user: ec2-user
  roles:
    - { role: registry, become: yes, become_method: sudo }
