# get slave jar from master
#
- name: Check if directory is present
  stat:
    path: '{{ jenkins_directory }}'
  register: jenkinsdir

- name: Check if jenkins slave file is present
  stat:
    path: '{{ jenkins_directory }}/slave.jar'
  register: slavejar

- name: Directory is present
  file:
    path='{{ jenkins_directory }}'
    state=directory
    mode=0770
  when: slavejar.stat.exists == False

- name: Download slave.jar file from master
  get_url: url='http://{{ groups.jenkinsmaster | join(" ") }}:8080/jnlpJars/slave.jar' dest='{{ jenkins_directory }}/slave.jar' mode=0775
  when: slavejar.stat.exists == False
  ignore_errors: true

- name: Slave container is running
  docker:
    image: sontags/centos7-jenkins-slave
    volumes: '{{ jenkins_directory }}:/var/jenkins'
    state: started
    command: '/bin/bash java -jar /var/jenkins/slave.jar -jnlpUrl http://{{ groups.jenkinsmaster | join(" ") }}:8080/computer/{{ groups.jenkinsslave | join(" ")}}/slave-agent.jnlp'
  register: running_container
